output_dir: /gpfs/project/yogah100/filter_assemble
sequencing:
   2000B: [
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/TOXO_ME49B_mouse_old_2022_01_27/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/05_05_2023_ME49_2000_1458cysts_105d_isolated_06_04_2023/05_05_2023_ToxoME49_2000_2020/ME49_2000_INF105/20230505_1010_MN26142_FAV34292_c98dd801/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_Inf_122d_740Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_inf_143d_1480_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_inf_21d_800_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_Inf_23d_640_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_Inf_66d_900_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_inf_85d_2396_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_Inf_43d_410_Cysts/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_02_2023_ToxoME49_2000/ME49_2000_Inf_56d_200_Cysts/recalled_with_guppy/all.fastq",    
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/2022.02.22_Toxo_ME49_B_mouse_old/recalled_with_guppy/all.fastq",    
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_04_2022_ToxoME49_B_old_mouse_DNase/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/07_04_2022_ToxoME49_B_old_mouse/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/17_07_23_ME49_2000-1500C/20230717_1230_MN35772_FAX02507_8c30b307/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/17_07_23_ME49_2000-1900C/20230717_1230_MN36487_FAX02441_0169adfb/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/17_07_23_ME49_2000-6000C/20230717_1230_MN40177_FAX02509_539b1423/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/20220906/recalled_with_guppy/all.fastq",  
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/23_06_2022_ToxoME49_two_runs_combined/recalled_with_guppy/all.fastq" ,
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2000_B/02_03_2023_ME49_2000_inf86d/recalled_with_guppy/all.fastq"      
    ]
   2020T: [
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2020_T/04_05_2022_ToxoME49T_2020/recalled_with_guppy/all.fastq",
    "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/nanopore_long_reads_fastq/samples_ToxoME49_2020_T/2021.12.03_TOXO_ME49_ATCC_new_ZK/recalled_with_guppy/all.fastq"
    ]
   2015T: [
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20240729_1314_MN39041_FAZ61091_eef4f29d/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq",
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20240729_1314_MN40175_FAZ60645_e7b0bf5d/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq",
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20240610_1411_MN40175_FAY46146_355a6c5e/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq",
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20241024_0917_P2S-01528-B_PAW56659_e2971904/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq",
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20241108_1155_MN23004_FBA90510_d8213e89/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq",
    "/gpfs/project/yogah100/ToxoME49_2015_2022/20241107_1405_MN40175_FAZ61068_e19d0750/recalled_with_dorado_and_Herro/combined_HERRO_simplex_with_duplex.fastq"]     
Minimizer: "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/fasta/human_and_mouse_genome_ToxoME49_GenBank_JACEHA000000000.1.mmi"
Mit: "/gpfs/project/projects/DiltheyLab/projects/Toxoplasma/fasta/collected_mit_sequences.fasta"
assemble: ["2015T"]
   




      

